### ISSUE TITLE
About getting Rich Edits 

### ISSUE THREAD

**Issue by jianghc2116** [SerVal-DTF/fixminer_source#26]
hello,I want to use Fixminer tool to get rich edits.But  when I use "java -jar FixPatternMiner-1.0.0-jar-with-dependencies.jar /Users/aaa/fixminer/src/main/resources/config.yml RICHEDITSCRIPT",I always fail .How will I do? Thank you very much!

**Comment by anilkoyuncu** [comment]
Hello,
Could you share the console output so that I can understand the nature of the error?

**Comment by jianghc2116** [comment]
![6063AF72-BC7D-4A56-BDBD-3AF6D441085F](https://user-images.githubusercontent.com/75469757/145829705-364f0ca5-6c7c-47d1-8eab-dd3a40c230d9.png)
The program run some time, and it become very very slow，almost stopped.Is this normal？How can I solve it? Thank you!

**Comment by jianghc2116** [comment]
![98D12565CD47F9AE35A5C1B8E9CBE40C](https://user-images.githubusercontent.com/75469757/145910458-c7b96107-557f-4e56-87a0-17df838e708c.jpg)
Now,it run about 10 hours, but still 11%.

**Comment by anilkoyuncu** [comment]
From the log it seems like Fixminer is running. Richeditscripts are kept in a redis instance. This is an in-memory database. If you computer does not have enough ram to store this will start paging and maybe will crash at some point. You check if you have any progress in by connecting the redis instance using the following comments.
[](https://github.com/TruX-DTF/fixminer_source#data-viewer)

In order check whether everything is working as expected I suggest you to use the setting in [the example config file](https://github.com/TruX-DTF/fixminer_source/blob/master/src/main/resources/config.yml). The important parameters here as follows:
    hunkLimit : 2
    patchSize : 50
    projectList : fuse
This will work on a very small subset. I recommend you to run the Fixminer with these setting and follow the steps [](https://github.com/TruX-DTF/fixminer_source#iv-step-by-step-execution) listed here. If everything is working smoothly then you can add new project change the other parameters.

**Comment by jianghc2116** [comment]
Thank you very much !
