### ISSUE TITLE
environmental problem

### ISSUE THREAD

**Issue by longbao8** [SerVal-DTF/fixminer_source#30]
Can fixminer be used in the win environment?

**Comment by anilkoyuncu** [comment]
It would be possible as all its dependencies are available also for windows. However, I would recommend docker instead. You can check [FlexiRepair](https://github.com/FlexiRepair/FlexiRepair) project for an example docker environment.

**Comment by longbao8** [comment]
When I use the Windows environment, I report an error.
ERROR - commons.py:shellCallTemplate - 'JAVA_HOME' is not recognized as an internal or external command,
operable program or batch file.

**Comment by anilkoyuncu** [comment]
Fixminer is currently supporting only Unix environments. However, it looks like you have a problem of setting java_home. I would recommend you google this first.
